#!/usr/bin/env python3
"""
WorkBuddy cross-device identity & memory sync script v3.9
=========================================================
Uses C:\\WorkBuddy\\_sync\\identity\\ as a transit dir to sync across devices.

v3.9 (2026-09-07):
  - [ROOT-FIX for user-level daily-log cross-workspace collision]
    collect_workspace_memories_to_user() now namespaces each workspace's daily
    logs into LOCAL/memory/<ws_name>/YYYY-MM-DD.md (subdir per workspace)
    instead of the previous FLAT LOCAL/memory/YYYY-MM-DD.md. The flat layout
    collided when multiple workspaces had a log for the same date (e.g. MyProject's
    8/26 桌游 vs Legal's 8/26 法务): shutil.copy2 with "newest mtime wins"
    overwrote the legitimate content with another workspace's content, then the
    polluted flat file propagated to WPS cloud and surfaced in any workspace
    that read from ~/.workbuddy/memory/ (the 8/26 incident surfaced in the
    Legal workspace diagnostic on 2026-09-07). After v3.9, cross-workspace
    date collisions are impossible because the per-workspace subdirs isolate
    the namespaces.
  - [MIGRATION] On the first v3.9 run, any legacy flat daily logs sitting at
    LOCAL/memory/YYYY-MM-DD.md are quarantined to
    LOCAL/_v39_legacy_flat_quarantine/YYYY-MM-DD.md (move-only, never delete).
    They are unreliable (already cross-polluted) and cannot be reassigned to a
    workspace. Both machines quarantine via the WPS sync of ~/.workbuddy/.
  - distribute_user_memory_to_workspaces() remains disabled (v3.7) -- the v3.9
    fix prevents NEW flat pollution at the user-level collect step. This is
    the "daily log layer" counterpart to v3.6's "MEMORY.md layer" fix.

v3.8 (2026-09-07):
  - [FIX] sync_workspace_memories now cleans non-.md files from BOTH the local
    and transit memory/ dirs BEFORE the bidirectional sync. During the 9/6
    C-drive + WeChat cleanup, ~47 one-off scripts/reports were wrongly written
    into .workbuddy/memory/; watch_sync pushed them to WPS cloud -> a
    "clean locally -> WPS copy reverse-pulls it back" zombie loop (verified).
    After the fix, memory/ physically contains only .md files (daily logs +
    project identity files); nothing else may enter.
  - [NEW] main() now runs a "clean dead IDE artifact-index references" step,
    calling the sibling cleanup_artifact_index.py. Root cause: artifact-index
    records the absolute-path URIs of every Read/Write/present_files call; even
    after the file is deleted from disk, the URI remains -> after restarting
    the IDE the artifact panel still shows the zombie entry. This step scrubs
    the active session(s) on every sync, so resurrection is impossible.
  - Same "draw the boundary" philosophy as v3.6: pin down exactly what memory/
    is allowed to be -- the only permitted content is .md.

v3.7 (2026-08-27):
  - [FIX] distribute_user_memory_to_workspaces() write-back disabled (after v3.6)
  - Fixed the memory-pollution incident caused by fanning user-level memory/
    out to every workspace (2026-08-27)

v3.5 (2026-07-09):
  - [ENH] Pre-push cleanup scope expanded to the entire _sync tree + every
    workspace .workbuddy/memory/ (root-causes the 1.1-wan -副本 copies left by
    the 7/6 conflict storm, and prevents future junk from being uploaded to cloud)
  - [NEW] Sync find_junk.py (scanner) / clean_junk.py (cleaner) to both machines
  - [FIX] .bat files switched to GBK encoding (fixes Windows CMD mojibake)

v3.6 (2026-08-02):
  - [ROOT-FIX for MEMORY.md cross-workspace overwrite pollution] collect/
    distribute only allows YYYY-MM-DD.md daily logs into the flat user-level
    memory/ namespace; project identity files (MEMORY.md / STATUS.md /
    DAILY_STATUS.md / HOME_WRAPUP.md / MORNING_BRIEF.md) are kept per-workspace
    -- flattening them let the "newest mtime wins" merge overwrite each other
    and fan back out to all workspaces (7/24 and 7/30 incidents). After the fix,
    project memory is no longer merged/fanned-out.

v3.4 (2026-07-08):
  - [FIX] Auto-clean WPS cloud conflict-copy files (-副本)
  - [FIX] Skip any file containing "副本" during sync (prevents sync storm)

v3.3 (2026-07-06):
  - Sync the daemon scripts themselves: watch_sync.py / start_sync.bat /
    AI_HANDOFF_GUIDE.md are now shared automatically across both machines,
    avoiding config drift
  - Inject user-level SOUL.md / USER.md cross-device sync iron rules

v3.2 (2026-07-06):
  - [ROOT-FIX for WPS cloud failure] Add HANDOFF.md to the sync list, routed
    through the transit dir instead of WPS cloud
  - _sync/HANDOFF.md is still generated by workspace_sync.py (machine section)
    + hand-written by AI, but cross-device flow now goes through
    _sync/identity/HANDOFF.md transit

v3.1 (2026-06-19):
  - find_workspaces() supports multiple workspace paths (company/home may differ)
  - Auto-detect: WORKSPACE_BASE, workspace dirs next to ~/.workbuddy/, current ws

v3.0 (2026-06-19):
  - User-level memory/ as the single source of truth, distributed to all local ws
  - On pull, auto-distribute user-level memory into each workspace .workbuddy/memory/
  - On push, reverse-collect each workspace's memory and merge into user-level memory/

v2.0 (2026-06-18):
  - Sync each workspace's .workbuddy/memory/ into the transit dir

Usage:
  python sync_identity.py              # bidirectional sync + collect + distribute
  python sync_identity.py push         # force push (run before leaving the machine)
  python sync_identity.py pull         # force pull + distribute (run on a new machine)
"""

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

HOME = Path.home()
LOCAL = HOME / ".workbuddy"
SYNC = Path(r"C:\WorkBuddy\_sync\identity")
# HANDOFF.md path (sits alongside the _sync/identity/ transit dir)
HANDOFF_LOCAL = Path(r"C:\WorkBuddy\_sync\HANDOFF.md")
HANDOFF_REMOTE = SYNC / "HANDOFF.md"

# Skip WPS cloud conflict-copy files (prevents sync storm)
SKIP_PATTERNS = {"-副本", "副本"}

# Only daily logs (YYYY-MM-DD.md) may enter the flat user-level memory/ namespace (v3.6)
_DAILY_RE = re.compile(r"^\d{4}-\d{2}-\d{2}\.md$")

# .workbuddy/memory/ may contain ONLY .md files (v3.8 defense)
# Includes daily logs (YYYY-MM-DD.md) and project identity files
# (MEMORY.md / STATUS.md / DAILY_STATUS.md / HOME_WRAPUP.md / MORNING_BRIEF.md etc.).
# Any temp script/report (.py / .txt / .log / .ps1 / .json ...) must NOT enter,
# or watch_sync will push it to WPS cloud and form a "clean -> reverse-pull"
# zombie loop (verified 2026-09-07).
_MEMORY_ALLOWED_EXTS = {".md"}

# Workspace root paths (multiple supported; company/home may differ)
# Auto-detected at runtime; these are the defaults
DEFAULT_WORKSPACE_BASES = [
    Path(r"C:\WorkBuddy"),          # configured path on both company & home machines
    HOME / "WorkBuddy",             # home default path
]

# Sibling script dir (v3.8 integrates artifact-index cleanup)
SCRIPT_DIR = Path(__file__).parent


try:
    from safe_remove import safe_remove
except ImportError:
    import os as _os
    import sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
    from safe_remove import safe_remove

def detect_workspace_bases() -> list[Path]:
    """Auto-detect the list of possible workspace root paths."""
    bases = []

    # 1. Read recently-used workspace paths from workspace-state.json
    state_file = LOCAL / "workspace-state.json"
    if state_file.exists():
        try:
            state = json.loads(state_file.read_text(encoding="utf-8"))
            for key in ("recentWorkspaces", "workspaces", "lastWorkspace"):
                if key in state and state[key]:
                    raw = state[key]
                    if isinstance(raw, str):
                        p = Path(raw)
                        if p.parent.exists():
                            bases.append(p.parent)
                    elif isinstance(raw, list):
                        for item in raw:
                            p = Path(item)
                            if p.exists() or p.parent.exists():
                                bases.append(p if p.is_dir() else p.parent)
        except Exception:
            pass

    # 2. Add defaults (dedup)
    for b in DEFAULT_WORKSPACE_BASES:
        if b not in bases:
            bases.append(b)

    # 3. Drop non-existent paths
    return [b for b in bases if b.exists()]


def find_workspaces(bases: list[Path] | None = None) -> list[Path]:
    """Scan all workspace roots; return workspaces containing a .workbuddy dir (dedup by name)."""
    if bases is None:
        bases = detect_workspace_bases()
    workspaces = []
    seen_names = set()
    for base in bases:
        if not base.exists():
            continue
        for child in sorted(base.iterdir()):
            if not child.is_dir():
                continue
            if child.name.startswith("."):
                continue
            wb_dir = child / ".workbuddy"
            if wb_dir.exists() and child.name not in seen_names:
                workspaces.append(child)
                seen_names.add(child.name)
    return workspaces


# ─── File sync utilities ────────────────────────────────────────────────

def is_skip_file(name: str) -> bool:
    """Check whether a filename should be skipped (WPS conflict copies etc.)."""
    for pat in SKIP_PATTERNS:
        if pat in name:
            return True
    return False


def is_daily_log(name: str) -> bool:
    """Only allow YYYY-MM-DD.md daily logs into the flat user-level memory/ namespace.

    v3.6 (2026-08-02): root-fix for MEMORY.md cross-workspace overwrite pollution.
    Project identity files (MEMORY.md / STATUS.md / DAILY_STATUS.md / HOME_WRAPUP.md /
    MORNING_BRIEF.md etc.) share the same name across workspaces; flattening them into
    one user-level memory/ dir let collect() overwrite each other by "newest mtime wins"
    (7/24 and 7/30 pollution incidents), then distribute() fan them back out to every
    workspace -> all become the same wrong content. Therefore collect/distribute strictly
    handle only daily logs; each workspace keeps its own project identity files.
    """
    return bool(_DAILY_RE.match(name))


def cleanup_duplicates(dirs: list[Path]) -> int:
    """Clean -副本 conflict files generated by WPS cloud. Returns count removed."""
    cleaned = 0
    for d in dirs:
        if not d.exists():
            continue
        for f in d.rglob("*"):
            if f.is_file() and is_skip_file(f.name):
                if safe_remove(f, "WPS conflict copy (-副本)"):
                    cleaned += 1
    if cleaned > 0:
        print(f"  [clean] Removed {cleaned} WPS conflict copies")
    return cleaned


def cleanup_memory_non_md(dir_path: Path) -> int:
    """Clean non-.md files from .workbuddy/memory/ (v3.8 defense).

    Historical incident (2026-09-07): 47 temp scripts/reports from the C-drive +
    WeChat cleanup were wrongly written into .workbuddy/memory/; watch_sync pushed
    them to WPS cloud, forming a "clean locally -> WPS copy reverse-pulls it back"
    zombie loop. After the fix, memory/ physically holds only .md files (daily logs +
    project identity files); resurrection is impossible.

    Returns count removed.
    """
    cleaned = 0
    if not dir_path.exists():
        return 0
    for f in list(dir_path.iterdir()):
        if not f.is_file():
            continue
        if f.suffix.lower() not in _MEMORY_ALLOWED_EXTS:
            if safe_remove(f, "non-.md file in memory/"):
                cleaned += 1
    if cleaned > 0:
        print(f"  [clean] {dir_path}: removed {cleaned} non-.md files")
    return cleaned


def sync_file(local: Path, remote: Path, force: str | None) -> str:
    """Sync a single file; return a status string.

    force=None  : newer side wins
    force="push": force local -> remote (push only if local exists, else skip)
    force="pull": force remote -> local (pull only if remote exists, else skip)
    """
    le = local.exists()
    re = remote.exists()

    if force == "push":
        if le:
            remote.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(local, remote)
            return "pushed"
        return "skipped"

    if force == "pull":
        if re:
            local.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(remote, local)
            return "pulled"
        return "skipped"

    # Bidirectional mode: newer side wins
    if not le and not re:
        return "none"
    if not le:
        local.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(remote, local)
        return "pulled"
    if not re:
        remote.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(local, remote)
        return "pushed"
    lm = local.stat().st_mtime
    rm = remote.stat().st_mtime
    if lm > rm:
        shutil.copy2(local, remote)
        return "pushed"
    if rm > lm:
        shutil.copy2(remote, local)
        return "pulled"
    return "same"


def sync_dir(local_dir: Path, remote_dir: Path, force: str | None) -> dict:
    """Sync a directory (recursive); return stats."""
    stats = {"pushed": 0, "pulled": 0, "skipped": 0}
    local_files: dict[Path, Path] = {}
    if local_dir.exists():
        for f in local_dir.rglob("*"):
            if f.is_file() and not is_skip_file(f.name):
                local_files[f.relative_to(local_dir)] = f
    remote_files: dict[Path, Path] = {}
    if remote_dir.exists():
        for f in remote_dir.rglob("*"):
            if f.is_file() and not is_skip_file(f.name):
                remote_files[f.relative_to(remote_dir)] = f
    for rel in set(local_files) | set(remote_files):
        r = sync_file(local_dir / rel, remote_dir / rel, force)
        if "push" in r:
            stats["pushed"] += 1
        elif "pull" in r:
            stats["pulled"] += 1
        else:
            stats["skipped"] += 1
    return stats


# ─── Workspace memory sync (v2.0) ──────────────────────────────────────

def sync_workspace_memories(bases: list[Path], force: str | None) -> dict:
    """Each workspace .workbuddy/memory/ <-> transit dir."""
    total = {"pushed": 0, "pulled": 0, "skipped": 0, "workspaces": 0}
    workspaces = find_workspaces(bases)
    if not workspaces:
        print("  [info] no workspaces found")
        return total

    for ws in workspaces:
        ws_name = ws.name
        local_mem = ws / ".workbuddy" / "memory"
        remote_mem = SYNC / "workspaces" / ws_name / "memory"
        remote_mem.mkdir(parents=True, exist_ok=True)
        # v3.8: clean non-.md files on both sides BEFORE syncing, to break the
        # "clean -> WPS reverse-pull" zombie loop
        cleanup_memory_non_md(local_mem)
        cleanup_memory_non_md(remote_mem)
        s = sync_dir(local_mem, remote_mem, force)
        status_parts = []
        if s["pushed"]:
            status_parts.append(f"pushed {s['pushed']}")
        if s["pulled"]:
            status_parts.append(f"pulled {s['pulled']}")
        if s["skipped"]:
            status_parts.append(f"skipped {s['skipped']}")
        status = " | ".join(status_parts) if status_parts else "no change"
        print(f"  [ws] {ws_name}/.workbuddy/memory/: {status}")
        for k in ("pushed", "pulled", "skipped"):
            total[k] += s[k]
        total["workspaces"] += 1

    return total


# ─── v3.0: user-level memory distribution ─────────────────────────────

def distribute_user_memory_to_workspaces(bases: list[Path]) -> int:
    """Write-back disabled since v3.7.

    Historical problem: if user-level memory/ daily logs were fanned out to every
    workspace, a single workspace's log would be copied to unrelated workspaces,
    causing "memory pollution" (2026-08-27 and later incidents).

    "Collect only, never write back" principle: workspace logs MAY be collected into
    user-level memory/ as a cross-project read-only index; but user-level memory/
    content is FORBIDDEN from being written back into each workspace's local
    .workbuddy/memory/. Each workspace maintains its own daily logs.

    Returns 0 always; kept only for caller compatibility.
    """
    return 0


def collect_workspace_memories_to_user(bases: list[Path]) -> int:
    """Collect & namespace each workspace's memory/*.md (daily logs only) into
    per-workspace subdirs under user-level memory/.

    v3.9 fix: each workspace's daily logs now land in
    LOCAL/memory/<ws_name>/YYYY-MM-DD.md instead of the previous FLAT
    LOCAL/memory/YYYY-MM-DD.md. The flat layout collided when two workspaces
    had a log for the same date -- shutil.copy2 "newest mtime wins" overwrote
    the other workspace's content, and the polluted flat file propagated to the
    WPS cloud (the 8/26 MyProject board-game vs Legal 法务 incident surfaced in
    the Legal workspace diagnostic on 2026-09-07). Per-workspace subdirs make
    date collisions impossible because each namespace is isolated.

    Migration: on every run, any legacy FLAT daily log still sitting directly at
    LOCAL/memory/YYYY-MM-DD.md is MOVED (never deleted) to
    LOCAL/_v39_legacy_flat_quarantine/YYYY-MM-DD.md. These are already
    cross-polluted and cannot be reassigned to a workspace, so they are only
    quarantined for forensic reference (move-only, per the safety red line).
    """
    user_mem = LOCAL / "memory"
    user_mem.mkdir(parents=True, exist_ok=True)

    # --- v3.9 migration: quarantine legacy FLAT daily logs (move-only) ---
    quarantine_dir = LOCAL / "_v39_legacy_flat_quarantine"
    for flat in sorted(user_mem.glob("*.md")):
        if not flat.is_file():
            continue
        if not is_daily_log(flat.name):
            continue  # keep project-identity files (MEMORY.md / STATUS.md) in place
        quarantine_dir.mkdir(parents=True, exist_ok=True)
        target = quarantine_dir / flat.name
        if not target.exists():
            shutil.move(str(flat), str(target))

    workspaces = find_workspaces(bases)
    if not workspaces:
        return 0

    collected = 0
    for ws in workspaces:
        ws_mem = ws / ".workbuddy" / "memory"
        if not ws_mem.exists():
            continue
        dest_dir = user_mem / ws.name
        dest_dir.mkdir(parents=True, exist_ok=True)
        for md_file in ws_mem.glob("*.md"):
            if not md_file.is_file():
                continue
            if not is_daily_log(md_file.name):
                continue  # v3.6: project identity files must not be flattened/fanned-out
            dest = dest_dir / md_file.name
            if not dest.exists() or md_file.stat().st_mtime > dest.stat().st_mtime:
                shutil.copy2(md_file, dest)
                collected += 1

    return collected


# ─── Main flow ─────────────────────────────────────────────────────────

def main():
    force = None
    if len(sys.argv) > 1:
        args = [a for a in sys.argv[1:] if not a.startswith("--")]
        if args:
            force = args[0].lower()
            if force not in ("push", "pull"):
                print(f"unknown direction: {force}")
                sys.exit(1)

    SYNC.mkdir(parents=True, exist_ok=True)
    total = {"pushed": 0, "pulled": 0, "skipped": 0}

    # Auto-detect workspace paths early (reused by cleanup + sync)
    bases = detect_workspace_bases()

    # --- ① Clean WPS conflict-copy files (prevent sync storm / junk upload) ---
    # Scope: the entire _sync transit tree + every workspace .workbuddy/memory/
    junk_roots = [SYNC]
    for ws in find_workspaces(bases):
        junk_roots.append(ws / ".workbuddy" / "memory")
    cleanup_duplicates(junk_roots)

    # --- ①.5 Clean dead IDE artifact-index references (v3.8 systematic root fix) ---
    # Root cause: artifact-index records the absolute-path URIs of every Read/Write/
    # present_files call; even after the file is deleted from disk, the URI remains
    # -> after restarting the IDE the artifact panel still shows the zombie entry.
    # Scrub the active session(s) on every sync.
    cleanup_script = SCRIPT_DIR / "cleanup_artifact_index.py"
    if cleanup_script.exists():
        try:
            cai_result = subprocess.run(
                [sys.executable, str(cleanup_script)],
                capture_output=True, text=True, timeout=30
            )
            if cai_result.returncode == 0 and cai_result.stdout.strip():
                for ln in cai_result.stdout.strip().split("\n"):
                    print(f"  [artifact-index] {ln}")
        except (subprocess.TimeoutExpired, OSError) as e:
            print(f"  [warn] artifact-index cleanup skipped: {e}")

    print("=" * 62)
    print("WorkBuddy cross-device sync v3.1")
    direction_label = {"push": "Push (local -> shared)", "pull": "Pull (shared -> local)"}.get(force, "Bidirectional (newer wins)")
    print(f"mode: {direction_label}")
    print(f"workspace paths: {[str(b) for b in bases]}")
    print("=" * 62)

    step = 0

    # --- ① Before leaving: collect each workspace's memory into user-level ---
    if force in (None, "push"):
        step += 1
        print(f"\n[{step}] Collect: workspace memory -> user-level memory/")
        n = collect_workspace_memories_to_user(bases)
        print(f"  collected {n} files")

    # --- ② User-level file sync ---
    step += 1
    print(f"\n[{step}] User-level: identity & memory files")
    for fname in [
        "IDENTITY.md", "SOUL.md", "USER.md",
        "MEMORY.md", "workspace-state.json",
    ]:
        r = sync_file(LOCAL / fname, SYNC / fname, force)
        arrow = {"pushed": "->", "pulled": "<-"}.get(r, ".")
        print(f"  {arrow} {fname}: {r}")
        if "push" in r:
            total["pushed"] += 1
        elif "pull" in r:
            total["pulled"] += 1
        else:
            total["skipped"] += 1

    # --- ②b v3.2: HANDOFF.md also uses the transit channel (bypasses dead WPS cloud) ---
    r = sync_file(HANDOFF_LOCAL, HANDOFF_REMOTE, force)
    arrow = {"pushed": "->", "pulled": "<-"}.get(r, ".")
    print(f"  {arrow} HANDOFF.md (transit channel): {r}")
    if "push" in r:
        total["pushed"] += 1
    elif "pull" in r:
        total["pulled"] += 1
    else:
        total["skipped"] = total.get("skipped", 0) + 1

    # --- ②c v3.3: sync the daemon + startup scripts (both machines auto-sync watch_sync itself) ---
    SYNC_SELF_DIR = Path(r"C:\WorkBuddy\_sync")
    for self_fname in ["watch_sync.py", "start_sync.bat", "AI_HANDOFF_GUIDE.md",
                       "find_junk.py", "clean_junk.py", "sync_identity.py"]:
        r = sync_file(SYNC_SELF_DIR / self_fname, SYNC / self_fname, force)
        arrow = {"pushed": "->", "pulled": "<-"}.get(r, ".")
        print(f"  {arrow} {self_fname} (daemon): {r}")
        if "push" in r:
            total["pushed"] += 1
        elif "pull" in r:
            total["pulled"] += 1
        else:
            total["skipped"] = total.get("skipped", 0) + 1

    s = sync_dir(LOCAL / "memory", SYNC / "memory", force)
    print(f"  [mem] memory/: pushed {s['pushed']} | pulled {s['pulled']} | skipped {s['skipped']}")
    for k in total:
        total[k] += s[k]

    # --- ③ Workspace memory sync (v2.0) ---
    step += 1
    print(f"\n[{step}] Workspace-level: each workspace .workbuddy/memory/ <-> transit")
    ws_total = sync_workspace_memories(bases, force)
    for k in total:
        total[k] += ws_total[k]

    # --- ④ After arriving at a new machine: distribute user-level memory to all workspaces ---
    if force in (None, "pull"):
        step += 1
        print(f"\n[{step}] Distribute: user-level memory/ -> each workspace")
        n = distribute_user_memory_to_workspaces(bases)
        ws_count = len(find_workspaces(bases))
        print(f"  {ws_count} workspaces, distributed {n} files")

    # --- Summary ---
    print("-" * 62)
    parts = [f"pushed {total['pushed']}", f"pulled {total['pulled']}", f"skipped {total['skipped']}"]
    if ws_total.get("workspaces"):
        parts.append(f"{ws_total['workspaces']} workspaces")
    print(f"summary: {', '.join(parts)}")
    print("=" * 62)


if __name__ == "__main__":
    main()
