#!/usr/bin/env python3
"""
WorkBuddy cross-device identity & memory sync script v3.4
=============================================
Syncs across devices via the C:\\WorkBuddy\\_sync\\identity\\ relay directory.

v3.5 (2026-07-09):
  - [Enhancement] Pre-push cleanup scope extended to the whole _sync tree plus each
    workspace's .workbuddy/memory/ (fully removes the ~11k copies left over from the
    7/6 conflict storm and keeps future junk from being uploaded to the cloud)
  - [New] Also syncs find_junk.py (junk scanner) / clean_junk.py (junk cleaner) to both machines
  - [Fix] .bat files now use GBK encoding (fixes garbled text in Windows CMD)

v3.6 (2026-08-02):
  - [Root fix for MEMORY.md cross-workspace overwrite pollution] collect/distribute only
    allow YYYY-MM-DD.md daily logs into the flat user-level memory/ namespace; project
    identity files (MEMORY.md/STATUS.md/DAILY_STATUS.md/HOME_WRAPUP.md/MORNING_BRIEF.md)
    share the same names across workspaces — if flattened, "newest mtime wins" makes them
    overwrite each other and fan back out to all workspaces (incidents on 7/24 and 7/30).
    After the fix, project memories are no longer merged/fanned out.

v3.4 (2026-07-08):
  - [Fix] Auto-clean WPS cloud-drive conflict-copy files (WPS "-copy" suffix files)
  - [Fix] Skip all files containing the WPS "-copy" suffix during sync (prevents sync storms)

v3.3 (2026-07-06):
  - Sync the daemon scripts themselves: watch_sync.py / start_sync.bat / AI_HANDOFF_GUIDE.md
    — both computers share the daemon and docs automatically, avoiding config drift
  - User-level SOUL.md / USER.md injected with cross-device sync ground rules

v3.2 (2026-07-06):
  - [Root fix for broken WPS cloud drive] Added HANDOFF.md to the sync list; it goes through
    the relay directory instead of the WPS cloud drive
  - _sync/HANDOFF.md is still generated by workspace_sync.py (machine section) + AI-written section
  - But cross-device transfer now goes through the _sync/identity/HANDOFF.md relay

v3.1 (2026-06-19):
  - find_workspaces() supports multiple workspace base paths (office/home may differ)
  - Auto-detection: WORKSPACE_BASE, workspace dirs next to ~/.workbuddy/, current workspace

v3.0 (2026-06-19):
  - User-level memory/ is the "single source of truth", distributed to all local workspaces
  - On pull, user-level memories are automatically distributed to each workspace's .workbuddy/memory/
  - On push, workspace memories are collected and merged back into user-level memory/

v2.0 (2026-06-18):
  - Sync each workspace's .workbuddy/memory/ to the relay directory

Usage:
  python sync_identity.py              # bidirectional sync + collect + distribute
  python sync_identity.py push        # force push (run before leaving this computer)
  python sync_identity.py pull        # force pull + distribute (run after switching to a new computer)
"""

import json
import re
import shutil
import sys
from pathlib import Path

HOME = Path.home()
LOCAL = HOME / ".workbuddy"
SYNC = Path(r"C:\WorkBuddy\_sync\identity")
# HANDOFF.md path (sits alongside the _sync/identity/ relay directory)
HANDOFF_LOCAL = Path(r"C:\WorkBuddy\_sync\HANDOFF.md")
HANDOFF_REMOTE = SYNC / "HANDOFF.md"

# Skip WPS cloud-drive conflict-copy files (prevents sync storms).
# NOTE: "-副本"/"副本" below are FUNCTIONAL — 副本 (Chinese for "copy") is the suffix
# WPS appends to conflict-copy filenames; these patterns are matched against names.
# Do NOT translate.
SKIP_PATTERNS = {"-副本", "副本"}

# Only daily logs (YYYY-MM-DD.md) may enter the flat user-level memory/ namespace (v3.6)
_DAILY_RE = re.compile(r"^\d{4}-\d{2}-\d{2}\.md$")

# Workspace root paths (multiple supported; office/home may differ)
# Auto-detected by the script; these are the defaults
DEFAULT_WORKSPACE_BASES = [
    Path(r"C:\WorkBuddy"),                          # office computer & configured home path
    HOME / "WorkBuddy",                             # default home path
]


def detect_workspace_bases() -> list[Path]:
    """Auto-detect the list of possible workspace root paths."""
    bases = []

    # 1. Read recently used workspace paths from workspace-state.json
    state_file = LOCAL / "workspace-state.json"
    if state_file.exists():
        try:
            state = json.loads(state_file.read_text(encoding="utf-8"))
            # Try to extract paths from the recentWorkspaces fields
            for key in ("recentWorkspaces", "workspaces", "lastWorkspace"):
                if key in state and state[key]:
                    raw = state[key]
                    if isinstance(raw, str):
                        p = Path(raw)
                        if p.parent.exists():
                            bases.append(p.parent)
                    elif isinstance(raw, list):
                        for item in raw:
                            p = Path(item)
                            if p.exists() or p.parent.exists():
                                bases.append(p if p.is_dir() else p.parent)
        except Exception:
            pass

    # 2. Add the default paths (deduplicated)
    for b in DEFAULT_WORKSPACE_BASES:
        if b not in bases:
            bases.append(b)

    # 3. Filter out non-existent ones
    return [b for b in bases if b.exists()]


def find_workspaces(bases: list[Path] | None = None) -> list[Path]:
    """Scan all workspace root paths and return workspaces containing a .workbuddy directory (deduplicated by name)."""
    if bases is None:
        bases = detect_workspace_bases()
    workspaces = []
    seen_names = set()
    for base in bases:
        if not base.exists():
            continue
        for child in sorted(base.iterdir()):
            if not child.is_dir():
                continue
            if child.name.startswith("."):
                continue
            wb_dir = child / ".workbuddy"
            if wb_dir.exists() and child.name not in seen_names:
                workspaces.append(child)
                seen_names.add(child.name)
    return workspaces


# ─── File sync helpers ─────────────────────────────────────────────────────────

def is_skip_file(name: str) -> bool:
    """Check whether a file name should be skipped (WPS conflict copies, etc.)."""
    for pat in SKIP_PATTERNS:
        if pat in name:
            return True
    return False


def is_daily_log(name: str) -> bool:
    """Only daily logs of the form YYYY-MM-DD.md may enter the flat user-level memory/ namespace.

    v3.6 (2026-08-02): root-cause fix for the MEMORY.md cross-workspace overwrite pollution.
    Project-level identity files (MEMORY.md / STATUS.md / DAILY_STATUS.md / HOME_WRAPUP.md /
    MORNING_BRIEF.md etc.) share the same names across workspaces; if flattened into the same
    user-level memory/ directory, collect would let "newest mtime wins" overwrite them
    (two pollution incidents on 7/24 and 7/30), and distribute would then fan the wrong
    content back out to all workspaces → everything becomes the same incorrect copy.
    Therefore collect/distribute strictly handle daily logs only; project identity files
    are kept independently by each workspace.
    """
    return bool(_DAILY_RE.match(name))


def cleanup_duplicates(dirs: list[Path]) -> int:
    """Clean up WPS cloud-drive "-copy" conflict files. Returns the number deleted."""
    cleaned = 0
    for d in dirs:
        if not d.exists():
            continue
        for f in d.rglob("*"):
            if f.is_file() and is_skip_file(f.name):
                try:
                    f.unlink()
                    cleaned += 1
                except OSError:
                    pass
    if cleaned > 0:
        print(f"  [clean] Removed {cleaned} WPS conflict copies")
    return cleaned


def sync_file(local: Path, remote: Path, force: str | None) -> str:
    """Sync a single file, returning a status string.

    force=None  : newer wins
    force="push": force local → remote (pushed only if local exists, otherwise skipped)
    force="pull": force remote → local (pulled only if remote exists, otherwise skipped)
    """
    le = local.exists()
    re = remote.exists()

    if force == "push":
        if le:
            shutil.copy2(local, remote)
            return "pushed"
        return "skipped"

    if force == "pull":
        if re:
            shutil.copy2(remote, local)
            return "pulled"
        return "skipped"

    # Bidirectional mode: newer wins
    if not le and not re:
        return "none"
    if not le:
        shutil.copy2(remote, local)
        return "pulled"
    if not re:
        shutil.copy2(local, remote)
        return "pushed"
    lm = local.stat().st_mtime
    rm = remote.stat().st_mtime
    if lm > rm:
        shutil.copy2(local, remote)
        return "pushed"
    if rm > lm:
        shutil.copy2(remote, local)
        return "pulled"
    return "same"


def sync_dir(local_dir: Path, remote_dir: Path, force: str | None) -> dict:
    """Sync a directory (recursively), returning stats."""
    stats = {"pushed": 0, "pulled": 0, "skipped": 0}
    local_files: dict[Path, Path] = {}
    if local_dir.exists():
        for f in local_dir.rglob("*"):
            if f.is_file() and not is_skip_file(f.name):
                local_files[f.relative_to(local_dir)] = f
    remote_files: dict[Path, Path] = {}
    if remote_dir.exists():
        for f in remote_dir.rglob("*"):
            if f.is_file() and not is_skip_file(f.name):
                remote_files[f.relative_to(remote_dir)] = f
    for rel in set(local_files) | set(remote_files):
        r = sync_file(local_dir / rel, remote_dir / rel, force)
        if "push" in r:
            stats["pushed"] += 1
        elif "pull" in r:
            stats["pulled"] += 1
        else:
            stats["skipped"] += 1
    return stats


# ─── Workspace memory sync (v2.0) ─────────────────────────────────────────────

def sync_workspace_memories(bases: list[Path], force: str | None) -> dict:
    """Each workspace's .workbuddy/memory/ ↔ relay directory."""
    total = {"pushed": 0, "pulled": 0, "skipped": 0, "workspaces": 0}
    workspaces = find_workspaces(bases)
    if not workspaces:
        print("  ℹ️  No workspaces found")
        return total

    for ws in workspaces:
        ws_name = ws.name
        local_mem = ws / ".workbuddy" / "memory"
        remote_mem = SYNC / "workspaces" / ws_name / "memory"
        remote_mem.mkdir(parents=True, exist_ok=True)
        s = sync_dir(local_mem, remote_mem, force)
        # NOTE: the status text below is INTENTIONALLY kept in Chinese — watch_sync.py
        # parses these output lines (it looks for 工作区 "workspace" and 推送 "pushed")
        # to count pushed files. This is an output-format contract between the two
        # scripts; do NOT translate.
        status_parts = []
        if s["pushed"]:
            status_parts.append(f"推送 {s['pushed']}")
        if s["pulled"]:
            status_parts.append(f"拉取 {s['pulled']}")
        if s["skipped"]:
            status_parts.append(f"跳过 {s['skipped']}")
        status = " | ".join(status_parts) if status_parts else "无变化"
        print(f"  📁 工作区 {ws_name}/.workbuddy/memory/: {status}")
        for k in ("pushed", "pulled", "skipped"):
            total[k] += s[k]
        total["workspaces"] += 1

    return total


# ─── v3.0: user-level memory distribution ─────────────────────────────────────

def distribute_user_memory_to_workspaces(bases: list[Path]) -> int:
    """Distribute user-level ~/.workbuddy/memory/*.md to all local workspaces.

    The user-level memory/ directory is the single source of truth.
    Every workspace on every computer reads the same memories.
    Returns the number of files distributed.
    """
    user_mem = LOCAL / "memory"
    if not user_mem.exists():
        return 0

    workspaces = find_workspaces(bases)
    if not workspaces:
        return 0

    distributed = 0
    for md_file in user_mem.glob("*.md"):
        if not md_file.is_file():
            continue
        if not is_daily_log(md_file.name):
            continue  # v3.6: project identity files must not be flattened/fanned out (avoids cross-workspace overwrite pollution)
        for ws in workspaces:
            ws_mem = ws / ".workbuddy" / "memory"
            ws_mem.mkdir(parents=True, exist_ok=True)
            dest = ws_mem / md_file.name
            # Only copy when the local copy is missing or the user-level one is newer
            if not dest.exists() or md_file.stat().st_mtime > dest.stat().st_mtime:
                shutil.copy2(md_file, dest)
                distributed += 1

    return distributed


def collect_workspace_memories_to_user(bases: list[Path]) -> int:
    """Collect and merge each workspace's memory/*.md into the user-level memory/.

    Run before leaving this computer to make sure the user level holds the latest
    memories from every workspace. Returns the number of files collected.
    """
    user_mem = LOCAL / "memory"
    user_mem.mkdir(parents=True, exist_ok=True)

    workspaces = find_workspaces(bases)
    if not workspaces:
        return 0

    collected = 0
    for ws in workspaces:
        ws_mem = ws / ".workbuddy" / "memory"
        if not ws_mem.exists():
            continue
        for md_file in ws_mem.glob("*.md"):
            if not md_file.is_file():
                continue
            if not is_daily_log(md_file.name):
                continue  # v3.6: project identity files must not be flattened/fanned out (avoids cross-workspace overwrite pollution)
            dest = user_mem / md_file.name
            if not dest.exists() or md_file.stat().st_mtime > dest.stat().st_mtime:
                shutil.copy2(md_file, dest)
                collected += 1

    return collected


# ─── Main flow ────────────────────────────────────────────────────────────────

def main():
    force = None
    if len(sys.argv) > 1:
        args = [a for a in sys.argv[1:] if not a.startswith("--")]
        if args:
            force = args[0].lower()
            if force not in ("push", "pull"):
                print(f"Unknown direction: {force}")
                sys.exit(1)

    SYNC.mkdir(parents=True, exist_ok=True)
    total = {"pushed": 0, "pulled": 0, "skipped": 0}

    # Auto-detect workspace paths (early, reused by cleanup and sync)
    bases = detect_workspace_bases()

    # --- ① Clean up WPS conflict-copy files (prevents sync storms / keeps junk off the cloud) ---
    # Cleanup scope: the whole _sync relay tree + each workspace's .workbuddy/memory/
    junk_roots = [SYNC]
    for ws in find_workspaces(bases):
        junk_roots.append(ws / ".workbuddy" / "memory")
    cleanup_duplicates(junk_roots)
    print("=" * 62)
    print(f"WorkBuddy Cross-Device Sync v3.1")
    direction_label = {"push": "Push (local→shared)", "pull": "Pull (shared→local)"}.get(force, "Bidirectional sync (newer wins)")
    print(f"Mode: {direction_label}")
    print(f"Workspace paths: {[str(b) for b in bases]}")
    print("=" * 62)

    step = 0

    # --- ① Before leaving this computer: collect workspace memories into the user level first ---
    if force in (None, "push"):
        step += 1
        print(f"\n[{step}] Collect: workspace memories → user-level memory/")
        n = collect_workspace_memories_to_user(bases)
        print(f"  Collected {n} files")

    # --- ② User-level file sync ---
    step += 1
    print(f"\n[{step}] User level: identity & memory files")
    for fname in [
        "IDENTITY.md", "SOUL.md", "USER.md",
        "MEMORY.md", "workspace-state.json",
    ]:
        r = sync_file(LOCAL / fname, SYNC / fname, force)
        arrow = {"pushed": "→", "pulled": "←"}.get(r, "·")
        print(f"  {arrow} {fname}: {r}")
        if "push" in r:
            total["pushed"] += 1
        elif "pull" in r:
            total["pulled"] += 1
        else:
            total["skipped"] += 1

    # --- ②b v3.2: HANDOFF.md also goes through the relay channel (bypassing the broken WPS cloud drive) ---
    r = sync_file(HANDOFF_LOCAL, HANDOFF_REMOTE, force)
    arrow = {"pushed": "→", "pulled": "←"}.get(r, "·")
    print(f"  {arrow} HANDOFF.md (relay channel): {r}")
    if "push" in r:
        total["pushed"] += 1
    elif "pull" in r:
        total["pulled"] += 1
    else:
        total["skipped"] = total.get("skipped", 0) + 1

    # --- ②c v3.3: sync the daemon and startup scripts (both computers sync watch_sync itself automatically) ---
    SYNC_SELF_DIR = Path(r"C:\WorkBuddy\_sync")
    for self_fname in ["watch_sync.py", "start_sync.bat", "AI_HANDOFF_GUIDE.md",
                       "find_junk.py", "clean_junk.py", "sync_identity.py"]:
        r = sync_file(SYNC_SELF_DIR / self_fname, SYNC / self_fname, force)
        arrow = {"pushed": "→", "pulled": "←"}.get(r, "·")
        print(f"  {arrow} {self_fname} (daemon): {r}")
        if "push" in r:
            total["pushed"] += 1
        elif "pull" in r:
            total["pulled"] += 1
        else:
            total["skipped"] = total.get("skipped", 0) + 1

    s = sync_dir(LOCAL / "memory", SYNC / "memory", force)
    print(f"  📁 memory/: pushed {s['pushed']} | pulled {s['pulled']} | skipped {s['skipped']}")
    for k in total:
        total[k] += s[k]

    # --- ③ Workspace memory sync (v2.0) ---
    step += 1
    print(f"\n[{step}] Workspace level: each workspace's .workbuddy/memory/ ↔ relay")
    ws_total = sync_workspace_memories(bases, force)
    for k in total:
        total[k] += ws_total[k]

    # --- ④ After arriving on a new computer: distribute user-level memories to all workspaces ---
    if force in (None, "pull"):
        step += 1
        print(f"\n[{step}] Distribute: user-level memory/ → each workspace")
        n = distribute_user_memory_to_workspaces(bases)
        ws_count = len(find_workspaces(bases))
        print(f"  {ws_count} workspaces, distributed {n} files")

    # --- Summary ---
    print("-" * 62)
    parts = [f"pushed {total['pushed']}", f"pulled {total['pulled']}", f"skipped {total['skipped']}"]
    if ws_total.get("workspaces"):
        parts.append(f"workspaces {ws_total['workspaces']}")
    print(f"Summary: {', '.join(parts)}")
    print("=" * 62)


if __name__ == "__main__":
    main()
